name: Unit Tests

on: [pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest

        permissions: read-all

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/cehckout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install
              run: npm ci
            - name: tests
              run: npm test
